name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Write compile time google-services.json file
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      run: echo $GOOGLE_SERVICES > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  detekt:
  
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v3

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.21.0-RC2
